### ISSUE TITLE
Potential Issue about t(v)%*%y being too close to a or b for CI

### ISSUE THREAD

**Issue by linnylin92** [linnylin92/binSegInf#8]
Try:

set.seed(44)
dat <- CpVector(100, c(0,5), 0.5)
y <- dat$data
obj <- fLasso_fixedSteps(y, 1)
poly <- polyhedra(obj, y)
contrast <- contrast_vector(obj, 1)
res <- confidence_interval(y, poly, contrast, gridsize = 50)
abs(contrast %*% y)

You'll see that the confidence interval does not contain t(v)%*%y. The reason is because t(v)%*%y is essentially v_lo, and that causes numeric problems.

**Comment by robohyun66** [comment]
close if fixed?
